// Mirrors Ground/Ground/Questions.swift — keep the two banks in sync.
export const CATEGORY_LABELS = {
  gratitude:  'gratitude & appreciation',
  compassion: 'compassion & kindness',
  values:     'values & meaning',
  emotions:   'emotions & inner life',
  grounding:  'grounding in the present',
  horizon:    'looking ahead',
  community:  'community & connection',
}

export const QUESTIONS = [
  ["What's something you're grateful for in this exact moment?", 'gratitude'],
  ["What's something in your surroundings you feel thankful for?", 'gratitude'],
  ["What's a routine or habit you're glad you have?", 'gratitude'],
  ["What's a comfort you enjoyed today — food, warmth, rest, music?", 'gratitude'],
  ["Who are you grateful for today, and why?", 'gratitude'],
  ["What's a past version of you that you feel thankful for?", 'gratitude'],
  ["What's something you have now that you once really wanted?", 'gratitude'],
  ["What's a piece of advice you're grateful you received?", 'gratitude'],
  ["What's a small joy from today you don't want to overlook?", 'gratitude'],
  ["What's something that went right today that you almost didn't notice?", 'gratitude'],
  ["Who made your day a little easier without realizing it?", 'gratitude'],
  ["What's an everyday object you'd genuinely miss if it disappeared?", 'gratitude'],
  ["What's a skill you have that you tend to take for granted?", 'gratitude'],
  ["What's something your body did for you today?", 'gratitude'],
  ["What's a place that always makes you feel more like yourself?", 'gratitude'],
  ["What's a song, book, or film that arrived in your life at exactly the right time?", 'gratitude'],
  ["What's a hard thing from your past that you're now quietly grateful for?", 'gratitude'],
  ["Who taught you something you still use almost every day?", 'gratitude'],
  ["What made you laugh recently?", 'gratitude'],
  ["What's a message you received that stayed with you?", 'gratitude'],
  ["What's something about where you live that you'd show off to a visitor?", 'gratitude'],
  ["What's a problem you no longer have that you used to worry about?", 'gratitude'],
  ["What's something a stranger did that you still think about?", 'gratitude'],
  ["What's an ordinary part of your day you'd want to keep exactly as it is?", 'gratitude'],
  ["Which friendship are you most thankful has lasted?", 'gratitude'],
  ["What's something you learned this week that you're glad to know?", 'gratitude'],
  ["What's one thing about today you'd want to remember a year from now?", 'gratitude'],
  ["What's a smell or sound that instantly makes you feel at home?", 'gratitude'],
  ["What's a decision you made that you're still glad about?", 'gratitude'],
  ["Who believed in you before you believed in yourself?", 'gratitude'],
  ["What part of your work or studies do you actually enjoy?", 'gratitude'],
  ["What's a season, time of day, or kind of weather you love, and why?", 'gratitude'],
  ["How can you be a little gentler with yourself right now?", 'compassion'],
  ["What's one thing you're willing to forgive yourself for today?", 'compassion'],
  ["What's something you're struggling with that deserves kindness, not criticism?", 'compassion'],
  ["How did you show up for yourself today, even in a tiny way?", 'compassion'],
  ["What's a mistake you can treat as a lesson instead of a failure?", 'compassion'],
  ["Who could use a bit of understanding from you right now?", 'compassion'],
  ["What's one kind thought you can offer yourself?", 'compassion'],
  ["What's a limit or boundary you honored that protected your energy?", 'compassion'],
  ["What's one way you could make tomorrow a bit easier on yourself?", 'compassion'],
  ["If a close friend felt like you do now, what would you say to them?", 'compassion'],
  ["What are you being hardest on yourself about lately?", 'compassion'],
  ["What would \"good enough\" look like today, instead of perfect?", 'compassion'],
  ["What's a feeling you've been judging yourself for having?", 'compassion'],
  ["What's something you need right now that you haven't asked for?", 'compassion'],
  ["What did you handle today better than you would have a year ago?", 'compassion'],
  ["Where are you expecting more of yourself than you would of anyone else?", 'compassion'],
  ["What's one thing you can take off your plate this week?", 'compassion'],
  ["Who's been on your mind, and what might they be going through?", 'compassion'],
  ["What's a part of you that's tired, and what would help it rest?", 'compassion'],
  ["What's a story you tell about yourself that might not be fair?", 'compassion'],
  ["What would it look like to give yourself the benefit of the doubt today?", 'compassion'],
  ["When did you last let someone help you, and how did it feel?", 'compassion'],
  ["What's a promise to yourself you kept recently, however small?", 'compassion'],
  ["What would you tell your younger self about what you're facing now?", 'compassion'],
  ["Who have you been quick to judge, and what might you be missing about them?", 'compassion'],
  ["What did you do today that took more effort than it looked?", 'compassion'],
  ["What does your body need from you right now?", 'compassion'],
  ["What's a worry you can set down until tomorrow?", 'compassion'],
  ["What's something you're still learning that you could be more patient with?", 'compassion'],
  ["Where did you show courage today, even if no one saw it?", 'compassion'],
  ["If you could gently redo one moment from today, what would you do differently?", 'compassion'],
  ["What's a kindness someone showed you that you could pass on?", 'compassion'],
  ["What mattered most to you about today?", 'values'],
  ["What did you do today that felt aligned with your values?", 'values'],
  ["What's an area of life where you want to show up more fully?", 'values'],
  ["What gave you a sense of purpose today, even briefly?", 'values'],
  ["What kind of person do you want to be in small, daily moments?", 'values'],
  ["What value felt strongest in you today — honesty, curiosity, kindness?", 'values'],
  ["What's one tiny action you took that moved you toward the life you want?", 'values'],
  ["Where did you choose what mattered over what was easiest today?", 'values'],
  ["What's something you said no to that protected what you care about?", 'values'],
  ["If today had a theme, what would it be?", 'values'],
  ["What did you spend most of your energy on today, and was it worth it?", 'values'],
  ["If you could only do three things tomorrow, what would they be?", 'values'],
  ["What's something you believe now that you didn't five years ago?", 'values'],
  ["What's a compliment you'd most like to be true about you?", 'values'],
  ["What's a rule you live by, even if you've never said it out loud?", 'values'],
  ["What would you do more of if no one were watching or judging?", 'values'],
  ["What's something you pretend to care about but really don't?", 'values'],
  ["What's something you care about but rarely make time for?", 'values'],
  ["Where did you compromise today, and do you feel okay about it?", 'values'],
  ["What's a choice you made recently that felt truly yours?", 'values'],
  ["Which of your habits best reflects who you want to be?", 'values'],
  ["What does a \"good day\" actually mean to you?", 'values'],
  ["What's something you'd stand behind even if it were unpopular?", 'values'],
  ["What would you want people to say you're like to be around?", 'values'],
  ["What's an obligation you've outgrown?", 'values'],
  ["What made you feel proud today, even quietly?", 'values'],
  ["What do you want to be known for that has nothing to do with work?", 'values'],
  ["When did you last feel completely absorbed in what you were doing?", 'values'],
  ["What's a trade-off you keep making that you'd like to rethink?", 'values'],
  ["What does \"enough\" look like for you right now?", 'values'],
  ["What's one thing you'd regret not doing this year?", 'values'],
  ["Whose approval are you still chasing, and do you actually need it?", 'values'],
  ["What's a question you keep coming back to in your life?", 'values'],
  ["What emotion is most noticeable in you right now?", 'emotions'],
  ["What's something that felt surprisingly heavy today?", 'emotions'],
  ["What's something that felt surprisingly light or easy today?", 'emotions'],
  ["What emotion did you try to push away, and why?", 'emotions'],
  ["When did you feel most at ease today?", 'emotions'],
  ["When did you feel most tense or on edge?", 'emotions'],
  ["What do you wish you could say out loud that you're holding inside?", 'emotions'],
  ["What's one emotion you can allow, just for a few breaths?", 'emotions'],
  ["What helped you regulate or soothe yourself today, even a little?", 'emotions'],
  ["What's taking up the most space in your mind right now?", 'emotions'],
  ["If your mood today were a color, what would it be?", 'emotions'],
  ["What's something you're looking forward to, even a little?", 'emotions'],
  ["What's been quietly bothering you that you haven't named yet?", 'emotions'],
  ["Where in your body are you holding today's stress?", 'emotions'],
  ["When did your mood shift today, and what caused it?", 'emotions'],
  ["What are you anxious about, and how likely is it, really?", 'emotions'],
  ["What's something you're excited about but haven't told anyone?", 'emotions'],
  ["What emotion has shown up most for you this week?", 'emotions'],
  ["What's a feeling that's hard for you to admit to others?", 'emotions'],
  ["What drained you today, and what refilled you?", 'emotions'],
  ["What's something you're resisting right now?", 'emotions'],
  ["Is there anything you're grieving lately, big or small?", 'emotions'],
  ["What are you curious about lately?", 'emotions'],
  ["What would you feel if you didn't have to be productive today?", 'emotions'],
  ["What's a reaction you had today that surprised you?", 'emotions'],
  ["What part of today do you keep replaying?", 'emotions'],
  ["What do you wish someone would notice about how you're doing?", 'emotions'],
  ["What's one word for how you feel, and one word for how you want to feel?", 'emotions'],
  ["What's been making you feel restless?", 'emotions'],
  ["What's a small win that lifted your mood recently?", 'emotions'],
  ["What are you avoiding thinking about?", 'emotions'],
  ["When did you feel most like yourself today?", 'emotions'],
  ["What does a perfectly balanced, ordinary Tuesday look like for you three years down the line?", 'horizon'],
  ["What mindsets, habits, or fears do you want to leave behind?", 'horizon'],
  ["If you were a guest on your own podcast five years from now, what would be the title of your episode, and what would be the most surprising pivot in your story?", 'horizon'],
  ["When looking at the unpredictable or seemingly chaotic parts of your future, where can you find the underlying patterns or peace?", 'horizon'],
  ["What will be your new anchor for daily discipline and routine?", 'horizon'],
  ["What is a deeply held assumption about your ideal path that you are willing to let go of to make room for unexpected opportunities?", 'horizon'],
  ["When you succeed, who is sitting at the table celebrating with you?", 'horizon'],
  ["What's one thing you want to be true about your life a year from now?", 'horizon'],
  ["What's a skill you'd love to have five years from now?", 'horizon'],
  ["What's something you're slowly building, even if no one sees it yet?", 'horizon'],
  ["What's a fear that's been quietly making your decisions for you?", 'horizon'],
  ["What's one small experiment you could try this month?", 'horizon'],
  ["What would you try if failing were completely private?", 'horizon'],
  ["What's a chapter of your life you're ready to close?", 'horizon'],
  ["What's a place you want to visit, and what draws you there?", 'horizon'],
  ["Who do you want to be closer to by this time next year?", 'horizon'],
  ["What does next week need from you?", 'horizon'],
  ["What's something future-you will thank you for starting today?", 'horizon'],
  ["What's a goal you've outgrown but haven't let go of?", 'horizon'],
  ["What would a slower, kinder version of your next month look like?", 'horizon'],
  ["What's a habit you want to start, and what's the smallest version of it?", 'horizon'],
  ["What do you hope you'll have stopped worrying about by next year?", 'horizon'],
  ["What's something you'd like to learn purely for the joy of it?", 'horizon'],
  ["What would you want to tell yourself on your next birthday?", 'horizon'],
  ["What's a risk that might be worth taking soon?", 'horizon'],
  ["What's a tradition you'd like to start?", 'horizon'],
  ["What part of your life now would you want to keep, no matter what changes?", 'horizon'],
  ["What's a decision you've been putting off, and what's the first step?", 'horizon'],
  ["How do you want to define \"community\" in your life?", 'community'],
  ["What is your favorite moment of teamwork and connection — what made it feel that way?", 'community'],
  ["Who is your hero, or someone you look up to, and what quality in them do you want to cultivate in yourself?", 'community'],
  ["What is an expectation you hold for the people around you, and do you hold yourself to that same standard?", 'community'],
  ["Who in your life consistently asks you the kinds of questions that make you pause and rethink your assumptions?", 'community'],
  ["If you were to host a dinner party, what is the feeling or atmosphere you want in that room?", 'community'],
  ["Who's someone you've been meaning to reach out to?", 'community'],
  ["Who do you feel most like yourself around?", 'community'],
  ["What's a conversation from this week that stuck with you?", 'community'],
  ["Who's someone new in your life you'd like to know better?", 'community'],
  ["What's one way you could make someone's day tomorrow?", 'community'],
  ["Who do you turn to when things fall apart, and do they know it?", 'community'],
  ["What's something you've learned from someone very different from you?", 'community'],
  ["When did you last feel truly listened to?", 'community'],
  ["What's a friendship that's changed, and how do you feel about it?", 'community'],
  ["Who would you call first with good news?", 'community'],
  ["Where is a place or group where you feel you belong?", 'community'],
  ["What do people usually come to you for?", 'community'],
  ["What's something you wish the people around you knew about you?", 'community'],
  ["What's a small ritual you share with someone?", 'community'],
  ["Who has shaped how you see the world without knowing it?", 'community'],
  ["How do you usually show people you care?", 'community'],
  ["What's a kindness you witnessed recently?", 'community'],
  ["Who have you lost touch with that you still think about?", 'community'],
  ["What's a relationship that asks a lot of you, and what does it give back?", 'community'],
  ["Who taught you how to be a good friend?", 'community'],
  ["What's one way you could give back to your community this month?", 'community'],
  ["What sensations can you feel in your body right now?", 'grounding'],
  ["What are three things you can see, two you can hear, one you can feel?", 'grounding'],
  ["What does your breathing actually feel like in this moment?", 'grounding'],
  ["What's a small detail around you that you hadn't noticed before?", 'grounding'],
  ["What tells you that you are safe enough in this moment?", 'grounding'],
  ["What's one thing you can let go of, just for the next minute?", 'grounding'],
  ["What's a small action you could take right now to feel 5% more settled?", 'grounding'],
  ["If you named this moment as a weather pattern, what would it be?", 'grounding'],
  ["What does the air feel like on your skin right now?", 'grounding'],
  ["What's the farthest-away sound you can hear?", 'grounding'],
  ["Where are you holding tension right now: jaw, shoulders, or hands?", 'grounding'],
  ["What's the softest thing within reach?", 'grounding'],
  ["What was the last thing you ate, and what did it actually taste like?", 'grounding'],
  ["How are your feet meeting the floor right now?", 'grounding'],
  ["Take three slow breaths. What changed, if anything?", 'grounding'],
  ["What's the light like where you are, and where is it coming from?", 'grounding'],
  ["What's one thing you're doing right now that you could do more slowly?", 'grounding'],
  ["What color shows up most in the space around you?", 'grounding'],
  ["What's one sound you've been tuning out all day?", 'grounding'],
  ["What's the most comfortable part of your body right now?", 'grounding'],
  ["If you paused everything for one minute, what would you notice first?", 'grounding'],
  ["What's happening right now that's actually okay?", 'grounding'],
  ["What's one object near you that has a story behind it?", 'grounding'],
  ["What are you carrying that doesn't belong to this moment?", 'grounding'],
  ["What's your posture telling you about how you feel?", 'grounding'],
  ["What's one thing you can stretch, tidy, or sip right now?", 'grounding'],
  ["When did you last look out a window, and what's out there now?", 'grounding'],
  ["What's the quietest thing you can hear?", 'grounding'],
  ["What's your energy from 1 to 10, and what's behind that number?", 'grounding'],
  ["What's one thing you could do in the next five minutes just for you?", 'grounding'],
]

const HISTORY_KEY = 'ground_prompt_history'
// When the bag runs out, this many of the most recent prompts sit out the next cycle
// so the end of one cycle can't immediately repeat at the start of the next.
const CARRY_OVER = 40

function readHistory() {
  try { return JSON.parse(localStorage.getItem(HISTORY_KEY) || '[]') } catch { return [] }
}

// Shuffle-bag pick: every prompt is shown once before any prompt repeats, and
// back-to-back prompts avoid sharing a category when possible.
export function pickQuestion() {
  let history = readHistory()
  let pool = QUESTIONS.filter(([q]) => !history.includes(q))
  if (pool.length === 0) {
    history = history.slice(-CARRY_OVER)
    pool = QUESTIONS.filter(([q]) => !history.includes(q))
  }
  const last = history[history.length - 1]
  const lastCategory = QUESTIONS.find(([q]) => q === last)?.[1]
  const varied = pool.filter(([, c]) => c !== lastCategory)
  const choices = varied.length ? varied : pool
  const item = choices[Math.floor(Math.random() * choices.length)]
  if (!item) return { question: 'how are you feeling right now?', category: 'emotions' }
  history.push(item[0])
  try { localStorage.setItem(HISTORY_KEY, JSON.stringify(history)) } catch {}
  return { question: item[0], category: item[1] }
}
